server:
  port: 7072
  servlet:
    context-path: /ekb
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:postgresql://192.168.12.139:5432/postgres
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver
  application:
    name: ekb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

