server:
  port: 7072
  servlet:
    context-path: /ekb
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:postgresql://192.168.12.139:5432/postgres
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver
  application:
    name: ekb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

auth:
  publicKey: -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwHCMz1PH4dDJfQHl3VMC
    SMQmAKZEdN0M2uBOYtBAf8uPUkSpBAzVwT8S80hpXojutivKIYVvs8DzvNJIFhJa
    FNYpn1FgQhKd2hCtt5+3rmXg7wo7F60XEK1abTUU8WcjuTcRe5QHPMUhHbNMYuPW
    pembwkS8gbWWp3rXKGQXT6AQyx3I9PMeZDwAcbPOzWjf3Wx4UP3IzqKjUiJ0QRDO
    dv2ZofrcxB4tYyGAD+gTIadl3vTBFX5T/SPb6TtEdUOJ1LxWlRP6w7pnq2+pnP9G
    L23cRCYOYlbDdUxUjOzfmuOZwoieeEV9Tc+JM0+7yHSleRZPbeg4yjzBf6rWxnHZ
    1QIDAQAB
    -----END PUBLIC KEY-----
  privateKey: -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAwHCMz1PH4dDJfQHl3VMCSMQmAKZEdN0M2uBOYtBAf8uPUkSp
    BAzVwT8S80hpXojutivKIYVvs8DzvNJIFhJaFNYpn1FgQhKd2hCtt5+3rmXg7wo7
    F60XEK1abTUU8WcjuTcRe5QHPMUhHbNMYuPWpembwkS8gbWWp3rXKGQXT6AQyx3I
    9PMeZDwAcbPOzWjf3Wx4UP3IzqKjUiJ0QRDOdv2ZofrcxB4tYyGAD+gTIadl3vTB
    FX5T/SPb6TtEdUOJ1LxWlRP6w7pnq2+pnP9GL23cRCYOYlbDdUxUjOzfmuOZwoie
    eEV9Tc+JM0+7yHSleRZPbeg4yjzBf6rWxnHZ1QIDAQABAoIBAFAQA2VWk/htJwbt
    PTchi/e+M5ldk2mTdf+yBqqxvcPtaslta2wV8vCdT0MMQ1pjWf1MpqHfpCODCWTr
    j7YvGG9G0rZH4uZaXHYXLk8REhhqpnSNKxyklM4JcW+x/+6XXJN4R7vEUGaGFUsI
    B6W06N7KHFVsx4inhfBT+SQC0Hf9hYfnNYsNwIQsKKJmhidkvwXS8c261bobwYJq
    zz0jKdLccJFRR1KjqREbAuenqQzAhZ2CDXKVu9Gu27Jlwp8uswiyet0gn0o5UKrR
    Xfv54a7SpMpNoNRt3KRXCqHAd7vHUSLkGY99tLg6X53FeKbs+3rTGmXDP3Hq+iDI
    7b9r/hkCgYEA4dPsqoVQoNLXPYslh1Ya4zRkv58MxDIxVpfvyalwKdIK+KfoleBN
    qu3P4TCzNJv2Nc2CeLBhYtD0tr6i+eFBsaAL0GGEBsvlKd43xZrVP4aqaPNfqn35
    iPI8CyYuSBvOyscPCg/rmzdIB4UJUXxDpU96hbF0NWoUdIwfT65rBiMCgYEA2iaj
    B/5yoSckO5AEGw6STBq/9KDFvWo8Mv/5TYxIJwAv+1a0XL+LhamAhyFbIdGPI85M
    ripiHcaWyV4u3Lyq+cSIiAH+SdTwFeWviUxbbx1L5RBEyva497eDcV9Hgbr97anf
    gJT5dNHUSodM8ivXJO59czyY61j/wi82I6lG06cCgYEAufzHIt1vPTTIbnhmLSMe
    O9ePzj2YzxEjj1TM+QJiTR8fSBFJvf4hGVCI78cjIIX+betWtD1Xx4Geuc8h/Lin
    WTod4L4fdVWB5EyPFGDjllE7kfo25Pyhgkc2alxEq8CzPFBbM4dPHOOXoBHSTdkR
    AVoG54rx0XgPZrlspDxbCo8CgYEAjVQept0nslPDW3svzb+g9AEYfwlxUgdzPK8s
    +hp53Bp4+2Hus2+8mjl39ROdEMnM7CuI7gSzUAsKQSbtQUBRnELBGSwBbB+x8t28
    3TxEuDXIp3vktYEl0AZp95b8ooVcYQ5+p7Tb79zIpggFx5azaU/AolmN0Fr2Rv2D
    G5NdOV0CgYEA0tl1y+g4K8M8CPxRFxNrIN0dP3LCaFqul4O4H0ztkB3zawqO0eZy
    mj30V42qIHCHN8Cb0hIXGfyOp/4akZdZUUXjNxuqc2QqPKFRfzHgQnDDxV/V7uXt
    Di3LPVdd6VgbvdJfj9CAvrGeTfOnblCB6PXQrNndob9Hl7krzvB3s6c=
    -----END RSA PRIVATE KEY-----

  clientId: ekb
  clientSecret: 1234567
